/**
 * Reads `data/gmat_vocab_stacks.json` and writes `shared/stacks/{canonicalId}.ts`
 * with `STACK_WORD_TEXTS` + `STACK_LEVELS` (pre-generation bootstrap).
 *
 * Usage: npm run sync:stack-modules
 */
import fs from 'node:fs'
import path from 'node:path'
import { CANONICAL_STACK_ORDER } from '../shared/canonicalStacks.ts'
import { readGlossary, repoRootFromScriptsDir } from './lib/glossary.ts'

function escapeString(s: string): string {
  return JSON.stringify(s)
}

function main() {
  const root = repoRootFromScriptsDir()
  const data = readGlossary()
  if (data.stacks.length !== CANONICAL_STACK_ORDER.length) {
    throw new Error(
      `Expected ${CANONICAL_STACK_ORDER.length} stacks in glossary, got ${data.stacks.length}`,
    )
  }

  const outDir = path.join(root, 'shared', 'stacks')
  fs.mkdirSync(outDir, { recursive: true })

  for (let i = 0; i < CANONICAL_STACK_ORDER.length; i++) {
    const spec = CANONICAL_STACK_ORDER[i]!
    const lore = data.stacks[i]!
    const texts = lore.items.map((it) => it.word)
    const levels = lore.items.map((it) => it.level)

    const lines: string[] = []
    lines.push(`/** Auto-generated by npm run sync:stack-modules — do not edit by hand. */`)
    lines.push(`import type { StackLevelBand } from '../stackPackTypes'`)
    lines.push(``)
    lines.push(`export const STACK_WORD_TEXTS = [`)
    for (const w of texts) {
      lines.push(`  ${escapeString(w)},`)
    }
    lines.push(`] as const`)
    lines.push(``)
    lines.push(`export const STACK_LEVELS: readonly StackLevelBand[] = [`)
    for (const lv of levels) {
      lines.push(`  '${lv}',`)
    }
    lines.push(`]`)
    lines.push(``)

    const outPath = path.join(outDir, `${spec.id}.ts`)
    if (fs.existsSync(outPath)) {
      const prev = fs.readFileSync(outPath, 'utf8')
      if (prev.includes('STACK_PACK') && process.env.STACK_SYNC_FORCE !== '1') {
        console.warn(
          `Skip ${spec.id}: promoted module (STACK_PACK). Set STACK_SYNC_FORCE=1 to overwrite with glossary words.`,
        )
        continue
      }
    }
    fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8')
    console.log('Wrote', path.relative(root, outPath), `(${texts.length} words)`)
  }

  console.log('Done.')
}

main()
